version: "2"
services:
  node1:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - "$PWD/app:/home/node/app"
    expose:
      - 8081
    command: "npm start"
  ngix:
    image: "nginx"
    volumes:
      - "$PWD/var/www:/var/www"
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/conf.d:/etc/nginx/conf.d"
    ports:
      - "8080:80"
    expose:
      - 80
