
version: "2"

services:
  node1:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/andrea/Documents/University/Didattica/RC2018/notebooks/LOAD_BALANCING_HTTPS/code/app:/home/node/app
    expose:
      - 8081
    command: "npm start"
  node2:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/andrea/Documents/University/Didattica/RC2018/notebooks/LOAD_BALANCING_HTTPS/code/app:/home/node/app
    expose:
      - 8081
    command: "npm start"
  ngix:
    image: "nginx"
    volumes:
    
      - /home/andrea/Documents/University/Didattica/RC2018/notebooks/LOAD_BALANCING_HTTPS/code/var/www:/var/www
      - /home/andrea/Documents/University/Didattica/RC2018/notebooks/LOAD_BALANCING_HTTPS/code/nginx.conf:/etc/nginx/nginx.conf
      - /home/andrea/Documents/University/Didattica/RC2018/notebooks/LOAD_BALANCING_HTTPS/code/conf.d:/etc/nginx/conf.d
      - /home/andrea/Documents/University/Didattica/RC2018/notebooks/LOAD_BALANCING_HTTPS/code/keys:/etc/nginx/keys
    ports:
      - "8080:80"
      - "4443:443"
    expose:
      - 80
      - 443